"""renamed video field

Revision ID: 4d378428eac7
Revises: aea30a52dd1d
Create Date: 2018-07-29 19:03:47.869795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d378428eac7'
down_revision = 'aea30a52dd1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_order_pos', table_name='question')
    op.create_unique_constraint("question_order_pos_key", 'question', ['order_pos'])
    op.add_column('video', sa.Column('s3_key', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_video_s3_key'), 'video', ['s3_key'], unique=True)
    op.drop_index('ix_video_url', table_name='video')
    op.drop_column('video', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('url', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
    op.create_index('ix_video_url', 'video', ['url'], unique=True)
    op.drop_index(op.f('ix_video_s3_key'), table_name='video')
    op.drop_column('video', 's3_key')
    op.drop_constraint("question_order_pos_key", 'question', type_='unique')
    op.create_index('ix_question_order_pos', 'question', ['order_pos'], unique=True)
    # ### end Alembic commands ###
