"""question and video tables

Revision ID: 7ed89945ee36
Revises: 51b88c570aec
Create Date: 2018-06-25 20:45:19.860141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed89945ee36'
down_revision = '51b88c570aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_timestamp'), 'video', ['timestamp'], unique=False)
    op.create_index(op.f('ix_video_url'), 'video', ['url'], unique=True)
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_index(op.f('ix_video_url'), table_name='video')
    op.drop_index(op.f('ix_video_timestamp'), table_name='video')
    op.drop_table('video')
    op.drop_table('question')
    # ### end Alembic commands ###
