"""fixed timestamp defaults

Revision ID: c72049272947
Revises: 4d378428eac7
Create Date: 2018-07-29 20:46:38.049059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72049272947'
down_revision = '4d378428eac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_creation_date', table_name='submission')
    op.drop_index('ix_submission_submission_date', table_name='submission')
    op.drop_index('ix_video_timestamp', table_name='video')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_video_timestamp', 'video', ['timestamp'], unique=False)
    op.create_index('ix_submission_submission_date', 'submission', ['submission_date'], unique=False)
    op.create_index('ix_submission_creation_date', 'submission', ['creation_date'], unique=False)
    # ### end Alembic commands ###
