"""added user agent to video

Revision ID: cfdf1799cca9
Revises: c72049272947
Create Date: 2018-07-29 20:54:46.366151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdf1799cca9'
down_revision = 'c72049272947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('user_agent', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'user_agent')
    # ### end Alembic commands ###
