"""add personality to submission

Revision ID: e0aa0dee701c
Revises: 0dcef413edcd
Create Date: 2018-09-10 18:36:33.020742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aa0dee701c'
down_revision = '0dcef413edcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('personality', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'personality')
    # ### end Alembic commands ###
