"""new fields in user model

Revision ID: eabae6939f55
Revises: 0369d1ab987d
Create Date: 2018-06-25 23:39:18.827400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabae6939f55'
down_revision = '0369d1ab987d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as bop:
        bop.drop_column('last_seen')
    # ### end Alembic commands ###
